In [135]:
#Q.1 Convert a 1D array to a 2D array with 2 rows
import numpy as np

a=np.array([10,20,30,40,50,60,70,80,90,100])

b=a.reshape(2,-1)

b

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [126]:
#.2 Get the common items between a and b


a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a, b)

c


array([2, 4])

In [128]:
#Q.3 Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])

b = a[(a >= 5) & (a <= 10)]

b

array([ 6,  9, 10])

In [127]:
#Q.4 Limit the number of items printed in python NumPy array a to a maximum of 6 elements.

a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14])

if len(a) > 6:
    print(np.concatenate([a[:3],[',,,'],a[-3:]]))
else:
    print(a)

['0' '1' '2' ',,,' '12' '13' '14']
